package com.example.innobottle.Entitites;

public class SensorData {

    /**
     * This class represents a single instance of a measurement of each load cell value
     * It holds a float array, typically with 9 measurement values (one value for each load cell)
     * The data is generated by the ESP32 and later retrieved
     */

    String timestamp;
    float[] loadCellValues;

    public SensorData(String timestamp, float[] loadCellValues){
        this.timestamp = timestamp;
        this.loadCellValues = loadCellValues;
    }

    public void setTimestamp(String newTimestamp){
        this.timestamp = newTimestamp;
    }

    public void setLoadCellValues(float[] newLoadCellValues){
        this.loadCellValues = newLoadCellValues;
    }

    public String getTimestamp(){
        return this.timestamp;
    }

    public float[] getLoadCellValues(){
        return this.loadCellValues;
    }
}
